# Generated by Django 4.1 on 2023-02-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
                ("courses", models.ManyToManyField(to="students2.course")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1024)),
                (
                    "dest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students2.teacher",
                        verbose_name="teacher_message",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students2.student",
                        verbose_name="student_message",
                    ),
                ),
            ],
        ),
    ]
